"""create items table

Revision ID: a192e264d34e
Revises: 1d4a505452c9
Create Date: 2026-01-21 00:48:09.402547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a192e264d34e'
down_revision: Union[str, Sequence[str], None] = '1d4a505452c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.alter_column('category', 'category_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('category', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_category_category_id'), 'category', ['category_id'], unique=False)
    op.drop_constraint(op.f('items_category_id_fkey'), 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'category', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(op.f('items_category_id_fkey'), 'items', 'categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_category_category_id'), table_name='category')
    op.alter_column('category', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('category', 'category_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey')),
    sa.UniqueConstraint('name', name=op.f('categories_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    # ### end Alembic commands ###
